site_name: 'TST'
site_description: 'TST'
edit_uri: https://github.com/tiaoshui/aragon-wiki/blob/master/docs/
theme:
  name: 'material'
  palette:
    primary: 'blue grey'
    accent: 'cyan'
  font:
      text: 'Overpass'
      code: 'Overpass Mono'
  logo: 'images/logo.svg'
  favicon: 'images/favicon.ico'
extra_css:
  - 'stylesheets/extra_style.css'
extra_javascript:
  - 'javascript/extra_js.js'
extra:
  social:
    - type: 'github'
      link: 'https://github.com/tiaoshui/'
  feature:
    tabs: false
markdown_extensions:
    - admonition
